"use client";
import { useState } from "react";
import katex from "katex";
import "katex/dist/katex.min.css";
const KEY="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"; const SITE="nawazpublication-rkh4.vercel.app";
function RenderText({text}:{text:string}){const p:any[]=[];let l=0;const r=/\$\$([\s\S]+?)\$\$|\$([^\$]+?)\$/g;let m,k=0;while((m=r.exec(text))!==null){if(m.index>l)p.push(<span key={k++} style={{whiteSpace:"pre-wrap"}}>{text.slice(l,m.index)}</span>);try{const h=katex.renderToString(m[1]||m[2],{displayMode:!!m[1],throwOnError:false});p.push(<span key={k++} dangerouslySetInnerHTML={{__html:h}} style={m[1]?{display:"block",margin:"12px 0"}:{}}/>);}catch{p.push(<span key={k++}>{m[1]||m[2]}</span>);}l=r.lastIndex;}if(l<text.length)p.push(<span key={k++} style={{whiteSpace:"pre-wrap"}}>{text.slice(l)}</span>);return<>{p}</>;}
export default function Home(){
  const [q,setQ]=useState(""); const [list,setList]=useState<any[]>([]); const [load,setLoad]=useState(false);
  function pdf(t:string){const w=window.open("","_blank");if(!w)return;w.document.write(`<html><head><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"><style>body{padding:24px;line-height:1.8;font-family:sans-serif}.wm{position:fixed;top:0;left:0;width:100%;height:100%;opacity:0.08;transform:rotate(-30deg);display:flex;flex-wrap:wrap;gap:60px;pointer-events:none;font-weight:bold;font-size:26px}</style></head><body><div class="wm">${Array(40).fill(SITE).map(s=>`<span>${s}</span>`).join("")}</div><h2>${SITE}</h2><hr><div>${t.replace(/</g,"&lt;")}</div><hr><button onclick="window.print()">Print / Save as PDF</button></body></html>`);w.document.close();}
  async function ask(){if(!q.trim())return;const myQ=q;setQ("");setList(s=>[...s,{u:true,t:myQ}]);setLoad(true);try{const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+KEY},body:JSON.stringify({model:"openai/gpt-oss-20b",messages:[{role:"system",content:"You are Nawaz Publication Teacher. Answer in same language as user. If Urdu script then Urdu script, if Roman Urdu then Roman Urdu. Teacher style, no code blocks. Use $x^2$ and $$ matrix $$"},{role:"user",content:myQ}]})});const d=await r.json();setList(s=>[...s,{u:false,t:d.error?d.error.message:d.choices[0].message.content}]);}catch(e:any){setList(s=>[...s,{u:false,t:e.message}]);}setLoad(false);}
  return(<div style={{minHeight:"100vh",background:"#f8f8f8",color:"#111",display:"flex",flexDirection:"column"}}><div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:list.length===0?"center":"flex-start",paddingTop:list.length===0?0:30}}>{list.length===0&&<div style={{textAlign:"center",marginBottom:28}}><h1 style={{fontSize:32,fontWeight:800,margin:0}}>Nawaz Publication</h1><p style={{color:"#666"}}>{SITE}</p></div>}<div style={{width:"100%",maxWidth:680,padding:"0 16px"}}>{list.map((m,i)=><div key={i} style={{background:"#fff",border:"1px solid #e5e5e5",padding:16,borderRadius:14,marginBottom:12,direction:/[\u0600-\u06FF]/.test(m.t)?"rtl":"ltr"}}><div style={{lineHeight:1.9}}><RenderText text={m.t}/></div>{!m.u&&<button onClick={()=>pdf(m.t)} style={{marginTop:10,background:"#111",color:"#fff",border:"none",padding:"8px 14px",borderRadius:20}}>📄 PDF</button>}</div>)}{load&&<div style={{textAlign:"center",color:"#888",padding:20}}>لکھا جا رہا ہے...</div>}</div></div><div style={{padding:16,background:"#fff",borderTop:"1px solid #e5e5e5",position:"sticky",bottom:0}}><div style={{maxWidth:680,margin:"0 auto",display:"flex",background:"#f1f1f1",borderRadius:30,padding:"5px 6px 5px 16px"}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="سوال لکھیں..." style={{flex:1,background:"transparent",border:"none",outline:"none",padding:10}}/><button onClick={ask} style={{background:"#111",color:"#fff",width:42,height:42,borderRadius:50,border:"none"}}>↑</button></div></div></div>)
}
